### PR TITLE
Update MANIFEST.in

### PR DESCRIPTION
**Pull request by goanpeca**
Fixes https://github.com/jupyter/nbformat/issues/206

### CODE REVIEW

**Comment by goanpeca** [comment]
I think I have asked this before, but are we still supporting 3.5 ?

**Review by blink1073 — APPROVED** [review]
Thanks!

**Comment by goanpeca** [comment]
@MSeal I can push a 5.1.2

**Comment by jamesmyatt** [comment]
@goanpeca , [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) would say Python 3.7+

**Comment by MSeal** [comment]
> I think I have asked this before, but are we still supporting 3.5 ?

No 3.5 should be dropped.

Generally we've left 3.6 support unless there's some active issue since it's still not [EOL](https://www.python.org/dev/peps/pep-0494/#:~:text=3.6%20Lifespan,-3.6%20will%20receive&text=0%20final%2C%20a%20final%203.6,so%20until%20approximately%202021%2D12.)

> @MSeal I can push a 5.1.2

Yeah, but give me a couple minute to test the wheel / dist between talking on this call :wink:

**Review by MSeal — APPROVED** [review]
LGTM works locally to build correctly

**Comment by MSeal** [comment]
Go for a 5.1.2 release -- I'll flag the other releases as bad on PyPI afterwards

**Comment by goanpeca** [comment]
https://pypi.org/project/nbformat/ is up @MSeal !

**Pull request merged**
