### PR TITLE
fix: Check if signature for notebook already exists before inserting

### LINKED ISSUE #99: Update store_signature to check for duplicate signatures
The [store_signature](https://github.com/jupyter/nbformat/blob/master/nbformat/sign.py#L207) method does not check if the signature is already in the store. 

The primary key used here is ``id``, so ``insert or ignore`` isn't really a check for duplicates. I think we should change the query to check if the signature exists first.

Not really an important issue - but still, thoughts ?

### PR DESCRIPTION
**Pull request by Madhu94**
Closes #99

### CODE REVIEW

**Comment by takluyver** [comment]
Looks fine to me, but I'd like @minrk to give it a quick look too.

**Comment by minrk** [comment]
Seems fine to me. Any chance for a failing test to catch this case? As you have correctly surmised, the INSERT OR IGNORE was meant to accomplish this already, so if that doesn't work, we haven't been testing this case (and nobody has ever saved the same notebook twice?).

**Comment by minrk** [comment]
Ah, I misunderstood the issue - we are wasting space, not creating errors. A+.

**Comment by Madhu94** [comment]
> and nobody has ever saved the same notebook twice?  

image

This is what my sqlite3 store looks like, after saving the notebook twice. (I deleted all signatures first). I don't _think_ this could be something happening on just my machine. 

>Any chance for a failing test to catch this case?  

You mean add an additional test in the test suite ?

**Comment by minrk** [comment]
Thanks!

**Pull request merged**
