### PR TITLE
Handle version on 3.7

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by vikramaditya91** [comment]
Could you please trigger a release for this bug as it is impacting all our plotly notebooks

**Comment by blink1073** [comment]
We haven't cut a release in a month, are you installing `nbformat` from a git checkout?

**Comment by vikramaditya91** [comment]
Not really. We had unpinned the version of `nbconvert` in our requirements.txt file which brought the faulty version of `nbformat`.
We have temporarily fixed it by pinnning the `nbformat` to 5.5.0

**Comment by blink1073** [comment]
Ah, my mistake, we did release 5.6 last week.

**Comment by blink1073** [comment]
Released

**Comment by vikramaditya91** [comment]
Thanks @blink1073 
Big fan of your work :)

**Pull request merged**
