### PR TITLE
ARM64: Add ARM64 jobs in Travis-CI

### PR DESCRIPTION
**Pull request by ossdev07**
Travis-CI has added support for ARM64. Added ARM64 jobs in Travis-CI.

### CODE REVIEW

**Comment by rgbkrk** [comment]
We should go ahead and remove our ARM builds, as it really slows down the builds and this is a pure python package. It's a bit unnecessary.

**Comment by rhenwood-arm** [comment]
I'm working with @ossdev07 on a downstream project. I have observed a slowdown too - and given there isn't any native code or binary release for this project, the Arm build task should be suspended.

**Comment by MSeal** [comment]
I'll revert the change in master then.

**Comment by MSeal** [comment]
Done: https://travis-ci.org/jupyter/nbformat?utm_medium=notification&utm_source=github_status

**Pull request merged**
