### PR TITLE
Add appveyor config

### PR DESCRIPTION
**Pull request by vidartf**
Adds a simple appveyor recipe (3.5 x64 / 2.7 x86, + codecov).

Based on top of #86 as it won't succeed the AppVeyor tests if not.

### CODE REVIEW

**Comment by Carreau** [comment]
> Based on top of #86 as it won't succeed the AppVeyor tests if not.

That seem to have been messed up either by git, or just in the GitHub UI. Would you mind trying to rebase and force-push a new branch ?

**Comment by Carreau** [comment]
From looking at the diff locally, I'm ok with it.
I'm just confused as to why the GitHub UI is confused about the commit history and diff.

**Comment by vidartf** [comment]
Rebased, and green. Someone with the necessary permissions would need to go an enable the project on th Jupyer account on Appveyor though.

**Comment by blink1073** [comment]
Done, appveyor building now.

**Comment by blink1073** [comment]
Thanks, @vidartf!

**Comment by mpacer** [comment]
I'm not sure why this would be on 4.4 since it was released as part of 4.3 earlier.

**Pull request merged**
