### PR TITLE
Start working on mutation issues in validate.

### PR DESCRIPTION
**Pull request by Carreau**
Step 1 toward #235

### CODE REVIEW

**Comment by Carreau** [comment]
cc @echarles

**Comment by echarles** [comment]
@Carreau I have just looked at the code change (not tested).

- `normalize` calls itself, is this intented? Should it be documented that it is a placeholder for future validations.
- -`_normalize`: called by `validate` and logs a warning, which is good as it will inform upstream libraries of potential issues (every cell should have an id...) and does not break anything.

**Comment by Carreau** [comment]
> * `normalize` calls itself, is this intented? Should it be documented that it is a placeholder for future validations.

It should have called the private `_normalize`. And I should have marked this as a draft.

**Comment by Carreau** [comment]
Rebased, test added and cleanup.

**Pull request closed without merging**
